name: Java CI

on: 
  push:
    branches:
      - feature/github-package
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy to Github Package Registry
      run: mvn clean package deploy -Dregistry=https://maven.pkg.github.com/dermatologist -Dtoken=${{ secrets.GITHUB_TOKEN }}


